site_name: pyasic
repo_url: https://github.com/UpstreamData/pyasic
nav:
- Introduction: "index.md"
- Miners:
    - Supported Miners: "miners/supported_types.md"
    - Standard Functionality: "miners/functions.md"
    - Miner Factory: "miners/miner_factory.md"
- Network:
    - Miner Network: "network/miner_network.md"
- Dataclasses:
    - Miner Data: "data/miner_data.md"
    - Error Codes: "data/error_codes.md"
    - Miner Config: "config/miner_config.md"
- Advanced:
    - RPC APIs:
        - Intro: "rpc/api.md"
        - BFGMiner: "rpc/bfgminer.md"
        - BMMiner: "rpc/bmminer.md"
        - BOSMiner: "rpc/bosminer.md"
        - BTMiner: "rpc/btminer.md"
        - CGMiner: "rpc/cgminer.md"
        - LUXMiner: "rpc/luxminer.md"
        - Unknown: "rpc/unknown.md"
    - Backends:
        - BMMiner: "miners/backends/bmminer.md"
        - BOSMiner: "miners/backends/bosminer.md"
        - BFGMiner: "miners/backends/bfgminer.md"
        - BTMiner: "miners/backends/btminer.md"
        - CGMiner: "miners/backends/cgminer.md"
        - LUXMiner: "miners/backends/luxminer.md"
        - VNish: "miners/backends/vnish.md"
        - ePIC: "miners/backends/epic.md"
        - Hiveon: "miners/backends/hiveon.md"
    - Classes:
        - Antminer X3: "miners/antminer/X3.md"
        - Antminer X5: "miners/antminer/X5.md"
        - Antminer X7: "miners/antminer/X7.md"
        - Antminer X9: "miners/antminer/X9.md"
        - Antminer X15: "miners/antminer/X15.md"
        - Antminer X17: "miners/antminer/X17.md"
        - Antminer X19: "miners/antminer/X19.md"
        - Antminer X21: "miners/antminer/X21.md"
        - Avalon 7X: "miners/avalonminer/A7X.md"
        - Avalon 8X: "miners/avalonminer/A8X.md"
        - Avalon 9X: "miners/avalonminer/A9X.md"
        - Avalon 10X: "miners/avalonminer/A10X.md"
        - Avalon 11X: "miners/avalonminer/A11X.md"
        - Avalon 12X: "miners/avalonminer/A12X.md"
        - Whatsminer M2X: "miners/whatsminer/M2X.md"
        - Whatsminer M3X: "miners/whatsminer/M3X.md"
        - Whatsminer M5X: "miners/whatsminer/M5X.md"
        - Innosilicon T3X: "miners/innosilicon/T3X.md"
        - Innosilicon A10X: "miners/innosilicon/A10X.md"
        - Goldshell X5: "miners/goldshell/X5.md"
        - Goldshell XMax: "miners/goldshell/XMax.md"
    - Base Miner: "miners/base_miner.md"
- Settings:
      - Settings: "settings/settings.md"

plugins:
  - mkdocstrings
  - search
